# Generated by Django 4.0 on 2022-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_secuser_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='secuser',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
