# Generated by Django 4.0 on 2022-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_secuser_address_alter_secuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuser',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='secuser',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
