# Generated by Django 4.0 on 2022-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_secuser_city_secuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuser',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
