# Generated by Django 4.0 on 2022-01-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_secuser_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('event_at', models.DateField(blank=True, null=True)),
                ('edate', models.DateTimeField(auto_now_add=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='Event')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.secuser')),
            ],
        ),
    ]
