# Generated by Django 4.0 on 2022-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='userapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('flatno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=60)),
                ('adharcardno', models.CharField(max_length=12)),
            ],
        ),
    ]
