# Generated by Django 4.0 on 2022-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userapp',
            new_name='Addmember',
        ),
    ]
