# Generated by Django 4.0 on 2022-01-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_userapp_addmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmember',
            old_name='flatno',
            new_name='flat',
        ),
    ]
