# Generated by Django 4.0 on 2022-01-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_flatno_addmember_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmember',
            old_name='adharcardno',
            new_name='adharcard',
        ),
    ]
