# Generated by Django 4.0 on 2022-01-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_adharcardno_addmember_adharcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Event'),
        ),
    ]
