# Generated by Django 4.0 on 2022-01-27 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_addmember_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=50)),
                ('ctypes', models.CharField(max_length=50)),
                ('cdes', models.TextField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('solvetime', models.DateTimeField(blank=True, null=True)),
                ('cby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addmember')),
                ('solveby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.secuser')),
            ],
        ),
    ]
