# Generated by Django 4.0 on 2022-01-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Complain'),
        ),
    ]
