# Generated by Django 4.0 on 2022-01-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_complain_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='pic',
            new_name='cpic',
        ),
    ]
