# Generated by Django 4.0 on 2022-02-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_complain_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtype', models.CharField(max_length=50)),
                ('gpic', models.FileField(upload_to='gallery')),
                ('gby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addmember')),
            ],
        ),
    ]
