# Generated by Django 4.0 on 2022-02-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.secuser'),
        ),
    ]
