# Generated by Django 4.0 on 2022-02-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_gallery_gby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(max_length=50)),
                ('ntitle', models.CharField(max_length=50)),
                ('ndes', models.TextField()),
                ('ntime', models.DateTimeField(blank=True, null=True)),
                ('nsendby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.secuser')),
            ],
        ),
    ]
