# Generated by Django 4.0 on 2022-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='ntime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
