# Generated by Django 4.0 on 2022-01-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userapp',
        ),
    ]
