# Generated by Django 4.0 on 2022-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
